### ISSUE TITLE
Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('f...

### ISSUE THREAD

**Issue by Cr0WD** [smkamranqadri/atom-angular-material-snippets#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [atom-angular-material-snippets](https://github.com/smkamranqadri/atom-angular-material-snippets) package, v1.0.0
### Stack Trace

Uncaught InvalidCharacterError: Failed to execute 'add' on 'DOMTokenList': The token provided ('fa-columns fa-rotate-270') contains HTML space characters, which are not valid in tokens.

```
At /C:/Users/fresh/.atom/packages/tool-bar/lib/tool-bar-button-view.js:45

Error: Failed to execute 'add' on 'DOMTokenList': The token provided ('fa-columns fa-rotate-270') contains HTML space characters, which are not valid in tokens.
    at Error (native)
    at new ToolBarButtonView (C:/Users/fresh/.atom/packages/tool-bar/lib/tool-bar-button-view.js:36:31)
    at ToolBarManager.addButton (C:/Users/fresh/.atom/packages/tool-bar/lib/tool-bar-manager.js:14:20)
    at Object.utils.addButton (file:///C:/Users/Денис/.atom/packages/tool-bar-almighty/lib/utils.coffee:17:11)
    at Object.utils.parseEntry (file:///C:/Users/Денис/.atom/packages/tool-bar-almighty/lib/utils.coffee:29:13)
    at Object.toolBarAlmighty.consumeToolBar (file:///C:/Users/Денис/.atom/packages/tool-bar-almighty/lib/tool-bar-almighty.coffee:34:11)
    at Provider.module.exports.Provider.provide (C:\Users\fresh\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\service-hub\lib\provider.js:30:52)
    at C:\Users\fresh\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\service-hub\lib\service-hub.js:55:26
    at doNTCallback0 (node.js:443:9)
    at process._tickCallback (node.js:372:13)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "autoHideMenuBar": true,
    "disabledPackages": [
      "autocomplete-paths",
      "php-cs-fixer",
      "tabs",
      "linter"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": []
  }
}
```
### Installed Packages

``` coffee
# User
auto-indent, v0.5.0
autoclose-html, v0.23.0
autocomplete-angular-material, v0.4.0
autocomplete-html-entities, v0.1.0
autocomplete-modules, v1.5.2
autocomplete-python, v1.8.1
autoupdate-packages, v1.3.1
color-picker, v2.2.1
emmet, v2.4.3
file-icons, v1.7.16
jade-bootstrap3-snippets, v0.3.0
jQuery, v1.2.4
merge-conflicts, v1.4.4
minimap, v4.24.7
pigments, v0.31.1
pretty-json, v1.4.1
snippets-jade, v0.2.0
tool-bar, v1.0.0
tool-bar-almighty, v0.6.1
tree-view-open-files, v0.3.0

# Dev
No dev packages
```

**Comment by smkamranqadri** [comment]
hi,

thanks for the approaching, please mention the steps to reproduce the error as you just mentioned.

[Enter steps to reproduce below:]

...
...

and if you want to send the pull request then i would love to merge.
